### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by agentx216** [MichaBrugger/booksidian_plugin#2]
Attempting to Sync to run everything. It sends up a hot key is not set yet. I've set a hotkey and all other settings appear to be correct and in proper format. I'm pointing to a specific folder not the default. I'm unable to run the plugin.

**Comment by MichaBrugger** [comment]
Thanks for reaching out! Unfortunately, I haven't been able to replicate the issue. Would you mind sending me a screenshot of your settings? That would help tremendously!

**Comment by agentx216** [comment]
![01](https://user-images.githubusercontent.com/99111988/152733899-22533543-6d29-40cb-912d-65f414a5ca4f.PNG)
![Capture2](https://user-images.githubusercontent.com/99111988/152733902-a5025294-bf14-4cbf-8684-aa72441ea857.PNG)
![Capture3](https://user-images.githubusercontent.com/99111988/152734090-637cdc25-6187-4d3e-ba4d-52b9eeee5a1e.PNG)

I've got the hotkey set and it does not

**Comment by MichaBrugger** [comment]
Thanks! Unfortunately, I can't reproduce the "no hotkey set" error. However, with the settings you provided I found a potential error: Could you try to change the URL to start with "https://www.goodreads.com/..."? I'll add a check for that these days since it won't work without the "https://". If this doesn't help, could you change the path of the output to a relative path? I currently haven't set it up to work with absolute paths (another thing I'll put on my list).

**Comment by agentx216** [comment]
Looks like the target folder was the issue.  Thanks.
