### ISSUE TITLE
Non-English titles with some symbols aren't parsing

### ISSUE THREAD

**Issue by ka1tzyu** [MichaBrugger/booksidian_plugin#6]
Hi! Thank you for this plugin. But I have an issue with parsing non-English titles. When I import these books in the obsidian, there are only English letters and numbers in the titles.

![](https://i.imgur.com/6fyNqLl.png)

But it must be "C# 4.0: полное руководство". '#', '.', ':' and all Cyrillic symbols are skipped.

**Comment by MichaBrugger** [comment]
Oh, my bad! I'll fix that asap!

**Comment by MichaBrugger** [comment]
@ka1tzyu It should be fixed. I ended up completely removing the parsing since it was not strictly necessary anyway (Goodreads should generally have clean enough data). I tested it with your particular book too and it worked properly. "полное руководство" is categorized as a subtitle though, so you'll find it there 👍🏼
