### ISSUE TITLE
Incorrect Published Date

### ISSUE THREAD

**Issue by creativefibro** [MichaBrugger/booksidian_plugin#9]
I have spent a couple of hours bringing in books and I have noticed that there is regularly a problem with the published date.

For instance the current book shows this in GoodReads: Published May 18th 2017 by HarperCollins (first published May 9th 2017)

But the date produced is: 2017-01-01

**Comment by MichaBrugger** [comment]
Could you maybe share your RSS feed, or a link to the specific book so I can test that?

**Comment by creativefibro** [comment]
This was the book: https://www.goodreads.com/book/show/34200289-eleanor-oliphant-is-completely-fine

- I don't know what is happening, I haven't made any further changes since the last batch I imported, but I went to import another batch and nothing is happening.

**Comment by MichaBrugger** [comment]
I checked it with that specific book and indeed it seems like the date-published is saved in the RSS feed without the month and the day - it says only "2017". And since Booksidian formats the field as a date, it turns it into "2017-01-01".

Once again, this is unfortunately nothing that I can impact/change in any way since it's purely relying on the data quality of Goodreads and has nothing to do with what my plugin does or doesn't do.
